name: ems
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  pdf: ^3.11.1
  open_file: ^3.4.00
  flutter_pdfview: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true # Enables Material Design icons

  # Uncomment and configure assets if using images or additional resources:
  # assets:
  #   - images/

  # Uncomment and configure fonts if using custom fonts:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
